export const VALID_TEAM_ABBREVIATIONS = [
  "ARI", "ATL", "BAL", "BUF", "CAR", "CHI", "CIN", "CLE",
  "DAL", "DEN", "DET", "GB", "HOU", "IND", "JAX", "KC",
  "LAC", "LAR", "LV", "MIA", "MIN", "NE", "NO", "NYG",
  "NYJ", "PHI", "PIT", "SEA", "SF", "TB", "TEN", "WAS",
] as const;

const SVG_OVERRIDES: Record<string, string> = {
  wsh: "WAS",
  jac: "JAX",
};

export function normalizeSvgAbbreviation(slug: string): string {
  const lower = slug.toLowerCase();
  return SVG_OVERRIDES[lower] ?? slug.toUpperCase();
}

const TEAM_NAME_MAP: Record<string, string> = {
  "arizona cardinals": "ARI",
  arizona: "ARI",
  cardinals: "ARI",
  "atlanta falcons": "ATL",
  atlanta: "ATL",
  falcons: "ATL",
  "baltimore ravens": "BAL",
  baltimore: "BAL",
  ravens: "BAL",
  "buffalo bills": "BUF",
  buffalo: "BUF",
  bills: "BUF",
  "carolina panthers": "CAR",
  carolina: "CAR",
  panthers: "CAR",
  "chicago bears": "CHI",
  chicago: "CHI",
  bears: "CHI",
  "cincinnati bengals": "CIN",
  cincinnati: "CIN",
  bengals: "CIN",
  "cleveland browns": "CLE",
  cleveland: "CLE",
  browns: "CLE",
  "dallas cowboys": "DAL",
  dallas: "DAL",
  cowboys: "DAL",
  "denver broncos": "DEN",
  denver: "DEN",
  broncos: "DEN",
  "detroit lions": "DET",
  detroit: "DET",
  lions: "DET",
  "green bay packers": "GB",
  "green bay": "GB",
  packers: "GB",
  "houston texans": "HOU",
  houston: "HOU",
  texans: "HOU",
  "indianapolis colts": "IND",
  indianapolis: "IND",
  colts: "IND",
  "jacksonville jaguars": "JAX",
  jacksonville: "JAX",
  jaguars: "JAX",
  "kansas city chiefs": "KC",
  "kansas city": "KC",
  chiefs: "KC",
  "los angeles chargers": "LAC",
  "la chargers": "LAC",
  chargers: "LAC",
  "los angeles rams": "LAR",
  "la rams": "LAR",
  rams: "LAR",
  "las vegas raiders": "LV",
  "las vegas": "LV",
  raiders: "LV",
  "miami dolphins": "MIA",
  miami: "MIA",
  dolphins: "MIA",
  "minnesota vikings": "MIN",
  minnesota: "MIN",
  vikings: "MIN",
  "new england patriots": "NE",
  "new england": "NE",
  patriots: "NE",
  "new orleans saints": "NO",
  "new orleans": "NO",
  saints: "NO",
  "new york giants": "NYG",
  "ny giants": "NYG",
  giants: "NYG",
  "new york jets": "NYJ",
  "ny jets": "NYJ",
  jets: "NYJ",
  "philadelphia eagles": "PHI",
  philadelphia: "PHI",
  eagles: "PHI",
  "pittsburgh steelers": "PIT",
  pittsburgh: "PIT",
  steelers: "PIT",
  "seattle seahawks": "SEA",
  seattle: "SEA",
  seahawks: "SEA",
  "san francisco 49ers": "SF",
  "san francisco": "SF",
  "49ers": "SF",
  "tampa bay buccaneers": "TB",
  "tampa bay": "TB",
  buccaneers: "TB",
  bucs: "TB",
  "tennessee titans": "TEN",
  tennessee: "TEN",
  titans: "TEN",
  "washington commanders": "WAS",
  washington: "WAS",
  commanders: "WAS",
};

export function resolveTeamAbbreviation(name: string): string | null {
  if (!name.trim()) return null;

  // Strip parenthetical text: "Dallas (from GB)" -> "Dallas"
  const cleaned = name.replace(/\s*\(.*\)\s*$/, "").trim().toLowerCase();

  return TEAM_NAME_MAP[cleaned] ?? null;
}
